package application

import "errors"

var (
	ErrSetupComplete                 = errors.New("setup is complete")
	ErrInvalidSetupToken             = errors.New("invalid setup token")
	ErrAccountNotFound               = errors.New("account not found")
	ErrInvalidCredentials            = errors.New("invalid credentials")
	ErrUnauthenticated               = errors.New("unauthenticated")
	ErrAccountDisabled               = errors.New("account disabled")
	ErrSelfUserOperation             = errors.New("cannot deactivate or delete own account")
	ErrRateLimited                   = errors.New("rate limited")
	ErrDependencyUnavailable         = errors.New("dependency unavailable")
	ErrPasswordHashBusy              = errors.New("password hashing capacity unavailable")
	ErrEmailAlreadyRegistered        = errors.New("email already registered")
	ErrEmailChangeNotFound           = errors.New("email change request not found")
	ErrInvalidEmailChange            = errors.New("invalid email change request")
	ErrInvalidEmailChangeCode        = errors.New("invalid email change code")
	ErrEmailChangeExpired            = errors.New("email change request expired")
	ErrEmailChangeResendTooSoon      = errors.New("email change resend too soon")
	ErrEmailChangeAttemptsExceeded   = errors.New("email change attempts exceeded")
	ErrAvatarNotFound                = errors.New("avatar not found")
	ErrInvalidPasswordResetToken     = errors.New("invalid password reset token")
	ErrForbidden                     = errors.New("forbidden")
	ErrRoleNotFound                  = errors.New("role not found")
	ErrRoleAlreadyExists             = errors.New("role already exists")
	ErrUserNotFound                  = errors.New("user not found")
	ErrInvitationNotFound            = errors.New("invitation not found")
	ErrRoleInUse                     = errors.New("role is in use")
	ErrImmutableRole                 = errors.New("system role is immutable")
	ErrLastSuperAdmin                = errors.New("at least one super administrator is required")
	ErrStaleRevision                 = errors.New("stale revision")
	ErrInvalidRoleSet                = errors.New("invalid role set")
	ErrInvitationPending             = errors.New("invitation is already pending")
	ErrInvitationInvalid             = errors.New("invalid invitation")
	ErrInvitationRoleForbidden       = errors.New("invitation role is outside actor permissions")
	ErrInvitationNotManageable       = errors.New("invitation is not manageable by actor")
	ErrPermissionScope               = errors.New("permission is outside actor scope")
	ErrMailNotConfigured             = errors.New("mail service is not configured")
	ErrInvalidMailSettings           = errors.New("invalid mail settings")
	ErrMailSettingsNotSaved          = errors.New("mail settings must be saved before testing")
	ErrMailTaskNotFound              = errors.New("mail task not found")
	ErrMailTaskSending               = errors.New("mail task is sending")
	ErrMailTaskNotRetryable          = errors.New("mail task is not retryable")
	ErrMailTaskDependency            = errors.New("mail task dependency unavailable")
	ErrMailTaskNotConfigured         = errors.New("mail task delivery is not configured")
	ErrSystemIdentityNotConfigured   = errors.New("system identity is not configured")
	ErrInvalidSystemIdentity         = errors.New("invalid system identity")
	ErrOperationLogNotFound          = errors.New("operation log not found")
	ErrOperationLogRetentionNotFound = errors.New("operation log retention not configured")
)
