import { expect, test, type Page } from '@playwright/test'

const enabled = process.env.E2E_USER_LIFECYCLE === '1'
const adminEmail = process.env.E2E_ADMIN_EMAIL ?? 'admin@example.com'
const targetEmail = process.env.E2E_TARGET_EMAIL ?? 'target@example.com'
const password = process.env.E2E_ADMIN_PASSWORD ?? 'Admin1!x'
async function login(page: Page, email: string) {
 await page.goto('/login')
 await page.getByLabel('Email', { exact: true }).fill(email)
 await page.getByLabel('Password', { exact: true }).fill(password)
 await page.getByRole('button', { name: 'Sign in', exact: true }).click()
 await expect(page).toHaveURL(/\/$/)
}

test('deactivates across browsers, restores only fresh login, and deletes while keeping history', async ({ page, browser }, testInfo) => {
 test.skip(!enabled, 'Requires an isolated installation with admin and disposable target accounts; target is permanently deleted.')
 test.setTimeout(120_000)
 const targetContext = await browser.newContext({ baseURL: testInfo.project.use.baseURL })
 const targetPage = await targetContext.newPage()
 try {
  await login(page, adminEmail)
  await login(targetPage, targetEmail)
  const identity = await targetPage.evaluate(async () => (await (await fetch('/api/auth/me')).json()).user)
  await page.goto('/users')
  const row = page.getByRole('row').filter({ hasText: targetEmail })
  await expect(row).toContainText('Active')
  await expect(page.getByRole('row').filter({ hasText: adminEmail }).getByRole('button', { name: 'Delete', exact: true })).toBeDisabled()
  await row.getByRole('button', { name: 'Deactivate', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Deactivate', exact: true }).click()
  await expect(row).toContainText('Disabled')
  await targetPage.bringToFront()
  await expect(targetPage).toHaveURL(/\/login$/, { timeout: 40_000 })
  await expect(targetPage.getByText('Your account has been deactivated. Contact an administrator.', { exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Filter by status' }).click()
  await page.getByRole('option', { name: 'Disabled', exact: true }).click()
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: 'Reactivate', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Reactivate', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(row).toHaveCount(0)
  await login(targetPage, targetEmail)
  await page.getByRole('combobox', { name: 'Filter by status' }).click()
  await page.getByRole('option', { name: 'All statuses', exact: true }).click()
  await row.getByRole('button', { name: 'Delete', exact: true }).click()
  const dialog = page.getByRole('dialog')
  const remove = dialog.getByRole('button', { name: 'Delete', exact: true })
  await expect(remove).toBeDisabled()
  await dialog.getByRole('textbox').fill('wrong@example.com'); await expect(remove).toBeDisabled()
  await dialog.getByRole('textbox').fill(targetEmail)
  const deletion = page.waitForResponse((response) => response.request().method() === 'DELETE' && response.url().includes('/api/users/'))
  await remove.click()
  expect((await deletion).status()).toBe(204)
  await expect(dialog).toBeHidden()
  await expect(row).toHaveCount(0)
  const sessionStatus = await targetPage.evaluate(async () => (await fetch('/api/auth/session-status')).status)
  expect(sessionStatus).toBe(401)
  await page.goto('/operation-logs')
  await page.locator('#operation-log-actor').fill(identity.id)
  await expect(page.locator('tbody')).toContainText('Deleted user')
  await expect(page.locator('tbody')).toContainText(targetEmail)
  await page.screenshot({ path: testInfo.outputPath('deleted-user-history.png'), fullPage: true })
  await page.locator('#operation-log-actor').fill('')
  await page.locator('#operation-log-action').fill('users.delete')
  await expect(page.locator('tbody')).toContainText('Delete user')
  await expect(page.locator('tbody')).toContainText('Deleted user')
  await page.getByRole('button', { name: 'Language settings' }).click()
  await page.getByRole('menuitemradio', { name: '简体中文', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('已删除用户')
 } finally { await targetContext.close() }
})
