import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { join } from 'node:path';
import { test } from 'node:test';
import { command, contaminateTemplate, gitEnvironment, modulePath, root, templateContaminants, temporaryDirectory } from './helpers.mjs';
import { assertAdminBaseline, generatedPath, requiredTemplateFiles } from './react-ts-baseline.mjs';

const requiredAssets = requiredTemplateFiles.map((path) => `template/${path}`);

function pack(source, destination) {
  const [packed] = JSON.parse(command('npm', ['pack', '--json', '--ignore-scripts', '--pack-destination', destination], { cwd: source }));
  return { path: join(destination, packed.filename), files: packed.files.map((file) => file.path) };
}

test('actual npm tarball installs without dev dependencies and its mapped bin generates away from source', async (t) => {
  const directory = await temporaryDirectory(t);
  const packed = pack(root, directory);
  for (const asset of ['dist/cli.js', 'dist/generate.js', 'dist/git.js', ...requiredAssets]) {
    assert.ok(packed.files.includes(asset), `Missing packed asset: ${asset}`);
  }
  assert.deepEqual(packed.files.filter((path) => path.startsWith('template/')).sort(), [...requiredAssets].sort());
  for (const file of packed.files) {
    assert.doesNotMatch(file, /(^|\/)(node_modules|\.git|\.env[^/]*|\.trellis|tests)(\/|$)|\.tsbuildinfo$|lock\.yaml$/);
    assert.ok(!file.startsWith('src/'), 'CLI TypeScript should not be needed at runtime');
  }

  const consumer = join(directory, 'consumer');
  await fs.mkdir(consumer);
  await fs.writeFile(join(consumer, 'package.json'), '{"private":true}');
  const env = gitEnvironment(directory);
  command('npm', ['install', '--offline', '--ignore-scripts', '--omit=dev', '--no-audit', '--no-fund', '--package-lock=false', packed.path], { cwd: consumer, env });
  const installed = join(consumer, 'node_modules/create-temvia');
  const metadata = JSON.parse(await fs.readFile(join(installed, 'package.json'), 'utf8'));
  assert.deepEqual(metadata.bin, { 'create-temvia': 'dist/cli.js' });
  assert.equal(metadata.dependencies, undefined);
  assert.equal(metadata.private, true);
  await assert.rejects(fs.stat(join(consumer, 'node_modules/typescript')), { code: 'ENOENT' });
  await assert.rejects(fs.stat(join(installed, 'node_modules')), { code: 'ENOENT' });
  assert.match(await fs.readFile(join(installed, 'dist/cli.js'), 'utf8'), /^#!\/usr\/bin\/env node\n/);
  assert.equal(command(process.execPath, [join(installed, 'dist/cli.js'), '--version'], { cwd: directory, env }).trim(), metadata.version);
  await assertAdminBaseline(join(installed, 'template/admin'), { materialized: false });

  const output = join(directory, 'generated project');
  const stdout = command('npm', ['exec', '--offline', '--no', '--', 'create-temvia', output, '--module', modulePath], { cwd: consumer, env });
  assert.match(stdout, /Initialized Git/);
  assert.deepEqual((await fs.readdir(output)).sort(), ['.git', '.gitignore', 'README.md', 'admin', 'api']);
  assert.equal(await fs.readFile(join(output, 'api/go.mod'), 'utf8'), `module ${modulePath}\n\ngo 1.27.0\n`);
  for (const asset of requiredAssets) {
    const relative = asset.slice('template/'.length);
    const generated = join(output, generatedPath(relative));
    assert.equal((await fs.stat(generated)).isFile(), true, `Missing generated file: ${relative}`);
    const installedBytes = await fs.readFile(join(installed, asset));
    assert.deepEqual(installedBytes, await fs.readFile(join(root, asset)), `Source-to-tarball bytes: ${relative}`);
    if (relative !== 'api/go.mod') {
      assert.deepEqual(await fs.readFile(generated), installedBytes, `Tarball-to-generated bytes: ${relative}`);
    }
  }
  await assertAdminBaseline(join(output, 'admin'));
  assert.equal(command('git', ['ls-files'], { cwd: output, env }), '');
  for (const unwanted of [
    'package.json', 'pnpm-workspace.yaml', 'web', 'admin/node_modules',
    'admin/pnpm-lock.yaml', 'admin/_gitignore', 'admin/_oxlintrc.json',
    'admin/.npmignore', 'admin/src/style.css', '_gitignore', '.npmignore',
  ]) {
    await assert.rejects(fs.stat(join(output, unwanted)), { code: 'ENOENT' });
  }
});

test('npm packing excludes local template installs, build output, secrets and tool state', async (t) => {
  const directory = await temporaryDirectory(t);
  const stage = join(directory, 'stage');
  await fs.mkdir(stage);
  await fs.copyFile(join(root, 'package.json'), join(stage, 'package.json'));
  await fs.cp(join(root, 'dist'), join(stage, 'dist'), { recursive: true });
  await fs.cp(join(root, 'template'), join(stage, 'template'), { recursive: true });
  await contaminateTemplate(join(stage, 'template'));
  const packed = pack(stage, directory);
  assert.deepEqual(packed.files.filter((path) => path.startsWith('template/')).sort(), [...requiredAssets].sort());
  for (const path of templateContaminants) assert.ok(!packed.files.includes(`template/${path}`), path);
});
